title: Incarcerated Wombats
description: >-
  Incarcerated Wombats is a hard rock band from the Long Island, New York
  area mostly active from 2008-2014.
url: "https://incarceratedwombats.com"
facebook_username: incarceratedwombats
twitter_username: followthewombat

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/:num/'
  title: ':num - :title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
sass:
  sass_dir: _sass
  style: compressed
