#!/bin/bash

if [ $TRAVIS_PULL_REQUEST == "true" ]; then
    exit 0
fi

set -e

rm -rf _site
mkdir _site

git clone https://24d9fda0472b6e3531d7ce8006e3e580cfe5cf76@github.com/KovuTheHusky/incarceratedwombats.com --branch gh-pages _site

bundle exec jekyll build

cd _site
git config user.email "kovuthehusky@gmail.com"
git config user.name "KovuTheHusky"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages
